/// Granular feature capabilities evaluated by [SubscriptionEntitlementService].
enum FeatureCapability {
  basicRiskMap,
  emergencyHub,
  basicHazardReporting,
  researchGis,
  demAnalysis,
  remoteSensing,
  gee,
  osintResearch,
  hydroAi,
  hecRas,
  sarValidation,
  environmentalHealth,
  exposureImpact,
  decisionSupport,
  advancedExport,
  researchProvenance,
  institutionalWorkspace,
  subscriptionAdministration,
  userAdministration,
  organizationAdministration,
  verificationAdministration,
  systemAdministration,
  ownerAdministration,
}
