name: riskpulse
description: "AI-Powered Disaster Risk Intelligence & Decision Support System"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_map: ^8.3.1
  latlong2: ^0.10.1
  google_generative_ai: ^0.4.5
  flutter_markdown: ^0.7.3+1
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  share_plus: ^10.0.2
  provider: ^6.1.2
  http: ^1.2.1
  audioplayers: ^6.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/riskpulse logo.png
    - lib/data/assets/test_hazards.geojson
    - lib/data/assets/hazards/landslide.geojson
    - lib/data/assets/hazards/flood.geojson
    - lib/data/assets/hazards/cloudburst.geojson
    - lib/data/assets/hazards/earthquake.geojson
    - lib/data/assets/hazards/forest_fire.geojson
    - lib/data/assets/hazards/avalanche.geojson
    - lib/data/assets/hazards/glof.geojson
    - lib/data/assets/hazards/major_landslides_polygons.geojson
    - lib/data/assets/hazards/kotropi_polygon.geojson
    - lib/data/assets/boundaries/hp_districts.geojson
    - lib/data/assets/boundaries/uk_districts.geojson
    - lib/data/assets/boundaries/states.geojson
    - lib/data/assets/boundaries/regions/hp.geojson
    - lib/data/assets/boundaries/regions/uk.geojson
