name: riskpulse
description: "AI-Powered Disaster Risk Intelligence & Decision Support System"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_map: ^8.3.1
  latlong2: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/data/assets/test_hazards.geojson
    - lib/data/assets/hazards/landslide.geojson
    - lib/data/assets/hazards/kotropi_polygon.geojson