name: riskpulse
description: "AI-Powered Disaster Risk Intelligence & Decision Support System"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_map: ^8.3.1
  latlong2: ^0.10.1
  google_generative_ai: ^0.4.5
  flutter_markdown: ^0.7.3+1
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  share_plus: ^10.0.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/data/assets/test_hazards.geojson
    - lib/data/assets/hazards/landslide.geojson
    - lib/data/assets/hazards/kotropi_polygon.geojson