import '../contracts/pw2r7_collision_contracts.dart';

class PW2R7CollisionEngine {
  /// Defines all 30 atomic features M01 through M30
  List<PW2R7AtomicFeature> getAtomicFeatures() {
    return const [
      PW2R7AtomicFeature(featureId: 'M01', description: 'Remote-sensing observation is ingested', isCoreToK10: true),
      PW2R7AtomicFeature(featureId: 'M02', description: 'Observation causes or represents a change/state mutation', isCoreToK10: true),
      PW2R7AtomicFeature(featureId: 'M03', description: 'Changed observation is associated with a spatial state', isCoreToK10: true),
      PW2R7AtomicFeature(featureId: 'M04', description: 'Spatial dependency relationship is represented', isCoreToK10: true),
      PW2R7AtomicFeature(featureId: 'M05', description: 'Affected spatial dependency closure is determined', isCoreToK10: true),
      PW2R7AtomicFeature(featureId: 'M06', description: 'Downstream spatial states are updated', isCoreToK10: true),
      PW2R7AtomicFeature(featureId: 'M07', description: 'Spatial state contributes to administrative state', isCoreToK10: true),
      PW2R7AtomicFeature(featureId: 'M08', description: 'Multiple spatial states can contribute to one administrative state', isCoreToK10: true),
      PW2R7AtomicFeature(featureId: 'M09', description: 'Administrative state contributes to risk state', isCoreToK10: true),
      PW2R7AtomicFeature(featureId: 'M10', description: 'Multiple administrative/spatial states can contribute to one risk state', isCoreToK10: true),
      PW2R7AtomicFeature(featureId: 'M11', description: 'Mutation propagates through spatial -> administrative -> risk relationship', isCoreToK10: true),
      PW2R7AtomicFeature(featureId: 'M12', description: 'Unrelated spatial/event regions remain isolated', isCoreToK10: true),
      PW2R7AtomicFeature(featureId: 'M13', description: 'Shared administrative dependency is preserved correctly after mutation', isCoreToK10: true),
      PW2R7AtomicFeature(featureId: 'M14', description: 'Shared risk dependency is preserved correctly after mutation', isCoreToK10: true),
      PW2R7AtomicFeature(featureId: 'M15', description: 'Historical state/version is preserved', isCoreToK10: true),
      PW2R7AtomicFeature(featureId: 'M16', description: 'Previous state can be reconstructed', isCoreToK10: true),
      PW2R7AtomicFeature(featureId: 'M17', description: 'Dependency topology can change', isCoreToK10: true),
      PW2R7AtomicFeature(featureId: 'M18', description: 'Addition/removal/redirection of dependency is handled', isCoreToK10: true),
      PW2R7AtomicFeature(featureId: 'M19', description: 'Downstream closure is recomputed after topology mutation', isCoreToK10: true),
      PW2R7AtomicFeature(featureId: 'M20', description: 'Current state and historical state coexist', isCoreToK10: true),
      PW2R7AtomicFeature(featureId: 'M21', description: 'Observation/state lineage is retained', isCoreToK10: true),
      PW2R7AtomicFeature(featureId: 'M22', description: 'State change remains attributable to source observation', isCoreToK10: true),
      PW2R7AtomicFeature(featureId: 'M23', description: 'Multiple events/regions can coexist without accidental merging', isCoreToK10: true),
      PW2R7AtomicFeature(featureId: 'M24', description: 'One event/region can affect a shared downstream administrative/risk state', isCoreToK10: true),
      PW2R7AtomicFeature(featureId: 'M25', description: 'Changing Event/Region A does not incorrectly rewrite Event/Region B', isCoreToK10: true),
      PW2R7AtomicFeature(featureId: 'M26', description: 'Complete spatial -> administrative -> risk crosswalk is represented as dependency structure', isCoreToK10: true),
      PW2R7AtomicFeature(featureId: 'M27', description: 'Dependency structure is updated in response to observation/state mutation', isCoreToK10: true),
      PW2R7AtomicFeature(featureId: 'M28', description: 'Historical versions remain valid after subsequent mutations', isCoreToK10: true),
      PW2R7AtomicFeature(featureId: 'M29', description: 'Shared downstream state is recalculated from remaining valid upstream contributors', isCoreToK10: true),
      PW2R7AtomicFeature(featureId: 'M30', description: 'Complete mechanism operates as one integrated technical system', isCoreToK10: true),
    ];
  }

  /// Evaluates Combination K01 through K10
  List<CombinationEvaluation> evaluateCombinations() {
    return const [
      CombinationEvaluation(
        combinationId: 'K01',
        description: 'C01 + C02 (Remote sensing mutation + Spatial closure)',
        includedComponents: ['C01', 'C02'],
        singleReferenceDisclosed: false,
        multiReferenceMosaicDisclosed: true,
        disclosingReferences: ['US8548248B2', 'US10036650B2'],
        missingCouplingRelationship: 'Disclosed across remote sensing imagery and GIS dependency literature.',
      ),
      CombinationEvaluation(
        combinationId: 'K02',
        description: 'C02 + C03 + C04 (Spatial -> Admin -> Risk propagation)',
        includedComponents: ['C02', 'C03', 'C04'],
        singleReferenceDisclosed: false,
        multiReferenceMosaicDisclosed: true,
        disclosingReferences: ['US10452652B2', 'US10036650B2'],
        missingCouplingRelationship: 'Geospatial event correlation prior art discloses spatial to admin mapping.',
      ),
      CombinationEvaluation(
        combinationId: 'K03',
        description: 'C03 + C04 + C08 + C09 (Shared Admin and Shared Risk propagation)',
        includedComponents: ['C03', 'C04', 'C08', 'C09'],
        singleReferenceDisclosed: false,
        multiReferenceMosaicDisclosed: true,
        disclosingReferences: ['US10452652B2', 'US10891340B2'],
        missingCouplingRelationship: 'Shared DAG node crosswalk propagation.',
      ),
      CombinationEvaluation(
        combinationId: 'K04',
        description: 'C05 + C08 + C09 (Cross-event isolation under shared dependencies)',
        includedComponents: ['C05', 'C08', 'C09'],
        singleReferenceDisclosed: false,
        multiReferenceMosaicDisclosed: true,
        disclosingReferences: ['US7441230B2', 'US10891340B2'],
        missingCouplingRelationship: 'Branch isolation in build DAGs applied to shared admin/risk nodes.',
      ),
      CombinationEvaluation(
        combinationId: 'K05',
        description: 'C06 + C10 (Historical state versioning + Topology mutation)',
        includedComponents: ['C06', 'C10'],
        singleReferenceDisclosed: false,
        multiReferenceMosaicDisclosed: true,
        disclosingReferences: ['CN117235153B', 'CN119443785A'],
        missingCouplingRelationship: 'Versioned provenance graphs with edge redirection.',
      ),
      CombinationEvaluation(
        combinationId: 'K06',
        description: 'C01 + C02 + C03 + C04 (Remote sensing mutation through spatial/admin/risk)',
        includedComponents: ['C01', 'C02', 'C03', 'C04'],
        singleReferenceDisclosed: false,
        multiReferenceMosaicDisclosed: true,
        disclosingReferences: ['US8548248B2', 'US10452652B2'],
        missingCouplingRelationship: 'Coupling satellite observation ingestion with multi-layer risk DAGs.',
      ),
      CombinationEvaluation(
        combinationId: 'K07',
        description: 'C01 + C02 + C08 + C09 (Remote sensing mutation + Shared admin/risk dependencies)',
        includedComponents: ['C01', 'C02', 'C08', 'C09'],
        singleReferenceDisclosed: false,
        multiReferenceMosaicDisclosed: true,
        disclosingReferences: ['US8548248B2', 'US10891340B2'],
        missingCouplingRelationship: 'Satellite raster mutation with shared crosswalk nodes.',
      ),
      CombinationEvaluation(
        combinationId: 'K08',
        description: 'C01 + C02 + C03 + C04 + C05 (Full pipeline with cross-event isolation)',
        includedComponents: ['C01', 'C02', 'C03', 'C04', 'C05'],
        singleReferenceDisclosed: false,
        multiReferenceMosaicDisclosed: true,
        disclosingReferences: ['US8548248B2', 'US10452652B2', 'US7441230B2'],
        missingCouplingRelationship: 'Multi-layer spatial risk DAG with cross-region isolation.',
      ),
      CombinationEvaluation(
        combinationId: 'K09',
        description: 'C01 + C02 + C03 + C04 + C05 + C06 (Full pipeline with isolation & versioning)',
        includedComponents: ['C01', 'C02', 'C03', 'C04', 'C05', 'C06'],
        singleReferenceDisclosed: false,
        multiReferenceMosaicDisclosed: true,
        disclosingReferences: ['US8548248B2', 'US10452652B2', 'US7441230B2', 'CN117235153B'],
        missingCouplingRelationship: 'Integrated pipeline with historical state versioning.',
      ),
      CombinationEvaluation(
        combinationId: 'K10',
        description: 'C01 + C02 + C03 + C04 + C05 + C06 + C08 + C09 + C10 (COMPLETE PW2R6 MINIMAL CANDIDATE)',
        includedComponents: ['C01', 'C02', 'C03', 'C04', 'C05', 'C06', 'C08', 'C09', 'C10'],
        singleReferenceDisclosed: false,
        multiReferenceMosaicDisclosed: true,
        disclosingReferences: ['CN119443785A', 'US8548248B2', 'US10036650B2', 'US20230267118A2', 'US7441230B2', 'US20200379978A1', 'CN117235153B', 'US10452652B2'],
        missingCouplingRelationship: 'Integrated remote-sensing-derived mutation across a 5-layer spatial-administrative-risk crosswalk with shared dependency recalculation, cross-event isolation, and historical state versioning in a single publication.',
      ),
    ];
  }
}
