import 'package:flutter/foundation.dart';

/// Represents a single analytical operation performed during a research workflow.
class AnalyticalStep {
  final String name;
  final String operationType;
  final Map<String, dynamic> parameters;
  final DateTime timestamp;
  
  /// Identifiers for the inputs used in this step (e.g., layer IDs).
  final List<String> inputReferences;
  
  /// Identifiers for the products generated by this step.
  final List<String> outputReferences;

  const AnalyticalStep({
    required this.name,
    this.operationType = 'generic',
    this.parameters = const {},
    required this.timestamp,
    this.inputReferences = const [],
    this.outputReferences = const [],
  });

  AnalyticalStep copyWith({
    String? name,
    String? operationType,
    Map<String, dynamic>? parameters,
    DateTime? timestamp,
    List<String>? inputReferences,
    List<String>? outputReferences,
  }) {
    return AnalyticalStep(
      name: name ?? this.name,
      operationType: operationType ?? this.operationType,
      parameters: parameters ?? Map<String, dynamic>.from(this.parameters),
      timestamp: timestamp ?? this.timestamp,
      inputReferences: inputReferences ?? List<String>.from(this.inputReferences),
      outputReferences: outputReferences ?? List<String>.from(this.outputReferences),
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AnalyticalStep &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          operationType == other.operationType &&
          mapEquals(parameters, other.parameters) &&
          timestamp == other.timestamp &&
          listEquals(inputReferences, other.inputReferences) &&
          listEquals(outputReferences, other.outputReferences);

  @override
  int get hashCode =>
      name.hashCode ^
      operationType.hashCode ^
      parameters.hashCode ^
      timestamp.hashCode ^
      inputReferences.hashCode ^
      outputReferences.hashCode;
}
