import 'package:flutter/foundation.dart';
import 'package:riskpulse/domain/gis/analytical_step.dart';
import 'package:riskpulse/domain/gis/spatial_concepts.dart';
import 'package:riskpulse/domain/location/geo_location.dart';

/// Immutable record capturing an analytical model assumption or default parameter.
@immutable
class AssumptionRegistryRecord {
  final String assumptionId;
  final String description;
  final dynamic parameterValue;
  final String unit;
  final String source;
  final String modelId;
  final bool isUserDefined;

  const AssumptionRegistryRecord({
    required this.assumptionId,
    required this.description,
    required this.parameterValue,
    required this.unit,
    required this.source,
    required this.modelId,
    this.isUserDefined = false,
  })  : assert(assumptionId.length > 0, 'assumptionId cannot be empty.'),
        assert(modelId.length > 0, 'modelId cannot be empty.');
}

/// Immutable contract representing an analytical research output payload.
///
/// SCIENTIFIC & ANALYTICAL GOVERNANCE:
/// 1. Preserves model limitations, assumptions, and execution modes (`REAL_DATA`, `SIMULATED`, `SYNTHETIC_FIXTURE`).
/// 2. Enforces explicit unit tracking and prevents conflation of exposure overlap with confirmed damage.
/// 3. Prevents probability claims unless generated by statistically calibrated probabilistic models.
@immutable
class ResearchAnalyticalContract {
  final String analysisId;
  final String analysisType;
  final List<String> inputReferences;
  final Map<String, dynamic> parameterSet;
  final String parameterVersion;
  final String modelId;
  final String modelVersion;
  final String executionMode; // REAL_DATA, SIMULATED, MOCK, SYNTHETIC_FIXTURE
  final String scientificStatus; // SOFTWARE_VALIDATED, UNCALIBRATED, PROVISIONAL
  final String uncertaintyState; // UNQUANTIFIED, CONFIDENCE_INTERVAL, BOUNDED_RANGE
  final String outputUnits;
  final MapExtent? spatialExtent;
  final DateTime analysisTimestamp;
  final List<AssumptionRegistryRecord> assumptions;
  final List<String> limitations;
  final AnalyticalStep provenanceStep;
  final bool isSyntheticFixture;

  const ResearchAnalyticalContract({
    required this.analysisId,
    required this.analysisType,
    required this.inputReferences,
    required this.parameterSet,
    this.parameterVersion = '1.0.0',
    required this.modelId,
    this.modelVersion = '1.0.0',
    this.executionMode = 'REAL_DATA',
    this.scientificStatus = 'SOFTWARE_VALIDATED',
    this.uncertaintyState = 'UNQUANTIFIED',
    required this.outputUnits,
    this.spatialExtent,
    required this.analysisTimestamp,
    this.assumptions = const [],
    this.limitations = const [],
    required this.provenanceStep,
    this.isSyntheticFixture = false,
  })  : assert(analysisId.length > 0, 'analysisId cannot be empty.'),
        assert(analysisType.length > 0, 'analysisType cannot be empty.'),
        assert(modelId.length > 0, 'modelId cannot be empty.');
}
