import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';
import 'package:share_plus/share_plus.dart';
import '../../data/models/risk_report.dart';
import '../risk_map/risk_map_screen.dart';

class ReportViewerScreen extends StatelessWidget {
  final RiskReport report;
  const ReportViewerScreen({super.key, required this.report});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        title: const Text('Intelligence Report'),
        backgroundColor: Colors.white,
        foregroundColor: const Color(0xFF0F172A),
        elevation: 0,
        actions: [
          IconButton(
            icon: const Icon(Icons.share_outlined),
            onPressed: () => _shareReport(),
          ),
          IconButton(
            icon: const Icon(Icons.download_outlined),
            onPressed: () => _simulateExport(context),
          ),
        ],
      ),
      body: Column(
        children: [
          _buildReportHeader(),
          Expanded(
            child: Markdown(
              data: report.content,
              selectable: true,
              styleSheet: MarkdownStyleSheet(
                h1: const TextStyle(fontSize: 24, fontWeight: FontWeight.w900, color: Color(0xFF0F172A), height: 2.0),
                h2: const TextStyle(fontSize: 20, fontWeight: FontWeight.w800, color: Color(0xFF0F172A), height: 1.8),
                h3: const TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: Color(0xFF0F172A), height: 1.6),
                p: const TextStyle(fontSize: 15, color: Color(0xFF334155), height: 1.6),
                tableBody: const TextStyle(fontSize: 13, color: Color(0xFF334155)),
                tableHead: const TextStyle(fontSize: 13, fontWeight: FontWeight.bold, color: Color(0xFF0F172A)),
                blockquoteDecoration: BoxDecoration(
                  color: const Color(0xFFF1F5F9),
                  borderRadius: BorderRadius.circular(8),
                  border: const Border(left: BorderSide(color: Color(0xFF6366F1), width: 4)),
                ),
              ),
            ),
          ),
          if (report.eventIds.isNotEmpty) _buildMapIntegration(context),
        ],
      ),
    );
  }

  Widget _buildReportHeader() {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 16),
      color: const Color(0xFFF8FAFC),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              _infoChip(Icons.people_outline, report.audience),
              const SizedBox(width: 8),
              _infoChip(Icons.description_outlined, report.depth),
              const Spacer(),
              Text(
                '${report.timestamp.day}/${report.timestamp.month}/${report.timestamp.year}',
                style: const TextStyle(fontSize: 12, fontWeight: FontWeight.w700, color: Color(0xFF94A3B8)),
              ),
            ],
          ),
          const SizedBox(height: 12),
          const Text(
            'GENERATED BY RISKPULSE AI INTELLIGENCE SYSTEM',
            style: TextStyle(fontSize: 9, fontWeight: FontWeight.w900, letterSpacing: 1.5, color: Color(0xFF6366F1)),
          ),
        ],
      ),
    );
  }

  Widget _infoChip(IconData icon, String label) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: const Color(0xFFE2E8F0)),
      ),
      child: Row(
        children: [
          Icon(icon, size: 14, color: const Color(0xFF64748B)),
          const SizedBox(width: 6),
          Text(label, style: const TextStyle(fontSize: 11, fontWeight: FontWeight.w700, color: Color(0xFF475569))),
        ],
      ),
    );
  }

  Widget _buildMapIntegration(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(24),
      decoration: const BoxDecoration(
        color: Colors.white,
        border: Border(top: BorderSide(color: Color(0xFFE2E8F0))),
      ),
      child: SafeArea(
        child: SizedBox(
          width: double.infinity,
          height: 56,
          child: ElevatedButton.icon(
            onPressed: () {
              Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) => RiskMapScreen(highlightDistricts: null), // We can extend RiskMapScreen to take specific IDs
                ),
              );
            },
            icon: const Icon(Icons.map_rounded),
            label: const Text('View Events on Risk Map', style: TextStyle(fontWeight: FontWeight.w800, fontSize: 16)),
            style: ElevatedButton.styleFrom(
              backgroundColor: const Color(0xFF0D9488),
              foregroundColor: Colors.white,
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
              elevation: 0,
            ),
          ),
        ),
      ),
    );
  }

  void _shareReport() {
    Share.share('${report.title}\n\n${report.content}\n\nGenerated by RiskPulse Intelligence');
  }

  void _simulateExport(BuildContext context) {
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text('Exporting report as PDF... (Feature in development)')),
    );
  }
}
